server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  flyway:
    baseline-on-migrate: true
    clean-disabled: false

wutsi:
  client-id: wutsi-tracking
  application:
    name: wutsi-tracking
    jobs:
      persister:
        cron: "0 0 * * * *" # every hour
      metric:
        cron: "0 0 1 * * *" # every day at 1AM

  platform:
    security:
      type: jwt
      api-key: ""
    stream:
      name: ${wutsi.application.name}
      type: local
      subscriptions:
        - wutsi-store-bff  # product tracking event
        - wutsi-shell-bff  # page navigation event
        - wutsi-web        # web tracking event
        - wutsi-order      # order events
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header
    storage:
      type: local

logging:
  level:
    root: INFO
    com.wutsi.analytics.tracking: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


