wutsi:
  client-id: wutsi-tracking
  platform:
    security:
      type: jwt
      api-key: ${API_KEY}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
    storage:
      type: aws
      aws:
        bucket: int-wutsi-track

