
name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -q -s settings.xml install

      - name: HerokuCLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install @heroku-cli/plugin-java

      - name: Heroku-Deploy-Test
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_TEST}}
          HEROKU_APP: wutsi-tracking-server-test
          CLOUDAMQP_URL: ${{secrets.CLOUDAMQP_URL_TEST}}
        run: |
          heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
          heroku buildpacks:clear --app ${HEROKU_APP}
          heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
          heroku config:set --app ${HEROKU_APP} APP_PROFILE=test
          heroku config:set --app ${HEROKU_APP} CLOUDAMQP_URL=${CLOUDAMQP_URL}
          heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
          heroku deploy:jar target/wutsi-tracking-server.jar --app ${HEROKU_APP}
          echo Health check....
          sleep 90
          curl -sSf https://${HEROKU_APP}.herokuapp.com/actuator/health >> /dev/null

      - name: Heroku-Deploy-Prod
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_PROD}}
          HEROKU_APP: wutsi-tracking-server-prod
          CLOUDAMQP_URL: ${{secrets.CLOUDAMQP_URL_PROD}}
        run: |
          heroku apps | grep ${HEROKU_APP} && echo 'app: ${HEROKU_APP} exists' ||  heroku apps:create ${HEROKU_APP}
          heroku buildpacks:clear --app ${HEROKU_APP}
          heroku buildpacks:add heroku/jvm --app ${HEROKU_APP}
          heroku config:set --app ${HEROKU_APP} APP_PROFILE=prod
          heroku config:set --app ${HEROKU_APP} CLOUDAMQP_URL=${CLOUDAMQP_URL}
          heroku addons -a ${HEROKU_APP} | grep papertrail && echo 'addon: papertrail exists' ||  heroku addons:create papertrail -a ${HEROKU_APP}
          heroku deploy:jar target/wutsi-tracking-server.jar --app ${HEROKU_APP}
          echo Health check....
          sleep 90
          curl -sSf https://${HEROKU_APP}.herokuapp.com/actuator/health >> /dev/null
