name: scheduled_run

on:
  schedule:
    - cron: "45 0,1,3 * * *"   # 12:45AM, 1:45AM, 3:45AM

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          curl -sSf https://wutsi-tracking-server-test.herokuapp.com/actuator/health >> /dev/null
