name: scheduled_run

on:
  schedule:
    - cron: "45 0,1,3,6,9,12,15,18,21 * * *"   # 12:45AM, 1:45AM, then every 3hr

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          curl -sSf https://wutsi-tracking-server-test.herokuapp.com/actuator/health >> /dev/null
